
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 12 12:37:53 IDT 2013
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ALU_SUB = 50;
  public static final int ALU_FILL_ONE = 36;
  public static final int INCREMENT = 7;
  public static final int ALU_LE = 44;
  public static final int CHANGED = 8;
  public static final int E_ASSIGN = 15;
  public static final int FORMAT = 2;
  public static final int F_ASSIGN = 16;
  public static final int R_SQUARE = 25;
  public static final int ALU_MULT = 51;
  public static final int ALU_EQ = 39;
  public static final int ALU_XOR = 48;
  public static final int NOT = 17;
  public static final int SEMICOLON = 28;
  public static final int AND = 18;
  public static final int TAG = 33;
  public static final int OPCODE = 5;
  public static final int OR = 19;
  public static final int COMMA = 30;
  public static final int ACCESSMODES = 3;
  public static final int COMPLEMENT = 6;
  public static final int ALU_AND = 46;
  public static final int ALU_NOT = 45;
  public static final int ALU_NE = 40;
  public static final int CODE = 4;
  public static final int IF = 13;
  public static final int ID = 55;
  public static final int R_BRACKET = 27;
  public static final int EOF = 0;
  public static final int DECIMAL = 31;
  public static final int ALU_DIV = 52;
  public static final int L_TRIANGULAR = 20;
  public static final int error = 1;
  public static final int L_CURLY = 22;
  public static final int R_CURLY = 23;
  public static final int NUMBER = 54;
  public static final int ALU_GR = 41;
  public static final int STRINGVAL = 56;
  public static final int ALU_FILL_ZERO = 35;
  public static final int ALU_L_SHIFT = 37;
  public static final int ALU_MOD = 53;
  public static final int COLON = 29;
  public static final int ALU_R_SHIFT = 38;
  public static final int ALU_GE = 43;
  public static final int R_TRIANGULAR = 21;
  public static final int L_SQUARE = 24;
  public static final int A_ASSIGN = 14;
  public static final int CLEAR = 9;
  public static final int END = 11;
  public static final int CYCLE = 57;
  public static final int L_BRACKET = 26;
  public static final int ALU_SUM = 49;
  public static final int ALU_LS = 42;
  public static final int HYPHEN = 32;
  public static final int ALU_OR = 47;
  public static final int HLT = 12;
  public static final int AM = 34;
  public static final int SET = 10;
}

