
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 10 19:11:46 IDT 2013
//----------------------------------------------------

package Assembler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMBER = 11;
  public static final int NEGATIVE = 8;
  public static final int EOF = 0;
  public static final int ORG = 2;
  public static final int BIN = 6;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int HEX = 4;
  public static final int NEWLINE = 9;
  public static final int DEC = 5;
  public static final int END = 3;
}

